// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB0HsHo-Cp01fwT2dGId8vNj1dr8HEwDA',
    appId: '1:376408084071:web:3e29b860105ebf48248ec2',
    messagingSenderId: '376408084071',
    projectId: 'flutterfire-carnaval',
    authDomain: 'flutterfire-carnaval.firebaseapp.com',
    storageBucket: 'flutterfire-carnaval.firebasestorage.app',
    measurementId: 'G-C6FQFB2D5N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoZ2wAMHq4snEfspmav56NGeeGb0b8GME',
    appId: '1:376408084071:android:d8e614b3473b3524248ec2',
    messagingSenderId: '376408084071',
    projectId: 'flutterfire-carnaval',
    storageBucket: 'flutterfire-carnaval.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH8e4OLLV3TCnxHvaurTsZSWNpmofC7d8',
    appId: '1:376408084071:ios:c7c80bfd678b338d248ec2',
    messagingSenderId: '376408084071',
    projectId: 'flutterfire-carnaval',
    storageBucket: 'flutterfire-carnaval.firebasestorage.app',
    iosBundleId: 'com.example.carnavalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAH8e4OLLV3TCnxHvaurTsZSWNpmofC7d8',
    appId: '1:376408084071:ios:c7c80bfd678b338d248ec2',
    messagingSenderId: '376408084071',
    projectId: 'flutterfire-carnaval',
    storageBucket: 'flutterfire-carnaval.firebasestorage.app',
    iosBundleId: 'com.example.carnavalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAB0HsHo-Cp01fwT2dGId8vNj1dr8HEwDA',
    appId: '1:376408084071:web:320be7861eb0af01248ec2',
    messagingSenderId: '376408084071',
    projectId: 'flutterfire-carnaval',
    authDomain: 'flutterfire-carnaval.firebaseapp.com',
    storageBucket: 'flutterfire-carnaval.firebasestorage.app',
    measurementId: 'G-MZJP4QQ8SD',
  );
}
